### ISSUE TITLE
Vendor publish requires step 3 to be done before step 2

### ISSUE THREAD

**Issue by almasaeed2010** [skovmand/mailchimp-laravel#1]
Hello,

I followed the steps you provided but artisan kept saying "nothing to publish" until I added the service provider (step 2) in my config/app.php. Only then vendor:publish worked. If I am not mistaken, step 3 should be placed before step 2 in the installation guide.

This is a great package, so thank you so much!

**Comment by skovmand** [comment]
You are right. Thanks!  

Of course it has to be in that order for it to work.
I corrected it now.

**Comment by almasaeed2010** [comment]
No problem. Thanks again!
