### ISSUE TITLE
Class "App\Services\App" not found error

### ISSUE THREAD

**Issue by 614mediagroup** [skovmand/mailchimp-laravel#10]
When trying to create a new mailchimp instance like shown in the docs. I get this error.

$mailchimp = App::make('Mailchimp');

**Comment by 614mediagroup** [comment]
Looks like that should be changed to $mailchimp = \App::make('Mailchimp'); in the docs as I didnt have a use App; line in my class.

**Comment by skovmand** [comment]
Of course you need to import the facade or just use `$mailchimp = app('Mailchimp');` in Laravel 5.
I'll update the docs - thanks for the improvement.
