### ISSUE TITLE
Describe features

### ISSUE THREAD

**Issue by simplenotezy** [skovmand/mailchimp-laravel#11]
Great package!

I have a few questions:
- I would like the ability to sign up my users without having them to accept first, how do I do this?
- How do I provide extra details, such as firstname, lastname, gender, etc?

**Comment by skovmand** [comment]
Hi.

This package is only a wrapper for the official mailchimp client. See: https://bitbucket.org/mailchimp/mailchimp-api-php.git or https://apidocs.mailchimp.com/api/

All the things you can do with the API, you can do through this package.
