### ISSUE TITLE
laravel 5.2 support

### ISSUE THREAD

**Issue by simplenotezy** [skovmand/mailchimp-laravel#14]

**Comment by jbrooksuk** [comment]
I see you added this in 7a8c238f91c6a434bc3c0540cd26e0331fb450d8 but it's wrong. Once it's fixed, can you then tag the release please?

**Comment by jbrooksuk** [comment]
I just released a package for Mailchimp, that uses a Manager setup allowing multiple connections. https://github.com/BlueBayTravel/Mailchimp

**Comment by skovmand** [comment]
Sorry, I forgot to tag it during the update process.. I guess it's christmas holidays...

**Comment by jbrooksuk** [comment]
Smoothly deleting comments there @skovmand :santa:

**Comment by skovmand** [comment]
Yeah.. It was more a promotion than related to the issue.
But it looks interesting, good luck with it.

Regards, Niels.

**Comment by jbrooksuk** [comment]
> Yeah.. It was more a promotion than related to the issue.

Sure.

Merry Christmas :christmas_tree:

**Comment by skovmand** [comment]
Thanks. Merry christmas to you too.

/ Niels.
