### ISSUE TITLE
Associative array required for lists subscribe

### ISSUE THREAD

**Issue by mabasic** [skovmand/mailchimp-laravel#2]
Hi, first of all congrats on this package, it is very nice.

I just wanted to point out that in your readme it says

```
$this->mailchimp->lists->subscribe($this->listId, $email);
```

but it should be:

```
$this->mailchimp->lists->subscribe($this->listId, ['email' => $email]);
```

When I tried it your way I kept getting this error:

```
Validation error: {"email":"Please enter a struct\/associative array"}
```

**Comment by skovmand** [comment]
Hi!

You're right, the example is wrong. 

My package just sends the message directly to the Mailchimp PHP Package, so the parameters for subscribe are those described in their Api: https://apidocs.mailchimp.com/api/2.0/lists/subscribe.php

I'll fix it later today.

Niels.

**Comment by skovmand** [comment]
And also: Thank you for notifying me!

**Comment by mabasic** [comment]
Np, happy to help :)

**Comment by rajankarthiks** [comment]
Hi skovmand,

I am also facing the same error. ({"email":"Please enter a struct\/associative array"}).

Can you tell me if you have updated the function.

And if you did, will it solve the problem by composer update command or should I have to redo the entire stuff.

Awaiting for you response at the earliest.

Thank you
