### ISSUE TITLE
Lumen, queue and one more question

### ISSUE THREAD

**Issue by davorpeic** [skovmand/mailchimp-laravel#21]
Hi,

1. Could you provide example for Lumen setup?
2. Do you have an idea how could we integrate Queue feature using this wrapper to postpone subscribing?
3. I see you are including entire mailchimp library, do we have all functions available from the library?

thanks

**Comment by dewwwald** [comment]
@davorpeic To add Queue mailchimp needs to merge my PR, https://bitbucket.org/mailchimp/mailchimp-api-php/pull-requests/22/restructure-the-code-this-is-so-the-curl/diff#comment-28513883

I changed the code and deployed to production without them merging it, I know it is dangerous.

**Comment by dewwwald** [comment]
I changed the code and deployed without them merging it.

**Comment by davorpeic** [comment]
Awesome, could you provide maybe a gist with code example how you used to create a job, I could also manually merge this changes? I already use mail::queue so table exist, but not sure I know how to add other jobs like this one :)

**Comment by dewwwald** [comment]
Here you go man. You'll obviously have to modify it to some extent. 

https://gist.github.com/dewwwald/b5ba9802d87af9801c7f45d663a86eae

**Comment by davorpeic** [comment]
Awesome, really appreciate the help, thanks!

**Comment by davorpeic** [comment]
Ok, I managed to implement this in Lumen 5.2, I had to make small changes in setup to get this work, not sure if @skovmand is open for PR to give an example how to implement in lumen.

@dewwwald thanks again, jobs are working as expected, I hope Mailchimp merge your update soon!

**Comment by skovmand** [comment]
If you send a PR with an example for Lumen, I'd be happy to merge it into README.md.

I don't know Lumen myself, and I have to admin I have no plans of learning it.

**Comment by davorpeic** [comment]
Thanks @skovmand I made PR, and I had to made small change to service, please check and let me know if any issue you have.

davor
