### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by NicolasVanhecke** [skovmand/mailchimp-laravel#23]
Always used skovmand, but as of today there is no support for Laravel 5.4 yet. I would hate to switch packages, any idea on when you could add support for 5.4?

[This is the cli output](https://gist.github.com/NicolasVanhecke/3b9c87775b025ad297b0a1721148952f)

**Comment by skovmand** [comment]
I just updated it to Laravel 5.4. However I haven't tested it yet.
Can you confirm that it works and give me some feedback?

Also note that it uses Mailchimp V2, which is deprecated from january 2017.

**Comment by NicolasVanhecke** [comment]
I can confirm the installation worked now! Thanks for that. 

Now I get this error, no idea if it is your package or the [mailchimp-api](https://github.com/drewm/mailchimp-api) from drewm that I also use. This is the [error in gist.github](https://gist.github.com/NicolasVanhecke/cbbb58782dd8120f1a3235eca4c6c8b5)

This is the [code](https://gist.github.com/NicolasVanhecke/ee63c29274a2d34815e9c5236f3175f3) I implemented. I am pretty sure I get the to the `catch` on line 30. But not sure on what is wrong.

**Comment by skovmand** [comment]
Glad to hear it works. As I understand the 5.4 changes it should work.

It looks like an error in the way you call Mailchimp. I haven't got time to
help you detect it though. Hope you'll solve it.

**Comment by NicolasVanhecke** [comment]
Glad to hear it is not the package. Will investigate the matter and my code further.
- Thanks for the quick update for 5.4!
