### ISSUE TITLE
Laravel Version Requirement for 5.5

### ISSUE THREAD

**Issue by adrianmejias** [skovmand/mailchimp-laravel#27]
Currently, the laravel framework requirement is set to **5.0 - 5.4**

**Comment by skovmand** [comment]
Yes we need 5.5! If you want it fixed quickly submit a pr. I can't look at it before the weekend.

**Comment by sadhakbj** [comment]
How can that be done ? I am using this package and I need to upgrade my system to 5.5. I am not able to upgrade my system because of this package.

**Comment by skovmand** [comment]
Thanks. I have tagged 1.0.8 with support for 5.5 now.

Out of interest, why are you still using this package? Its using the old
Mailchimp v2 api.

Niels.

**Comment by sadhakbj** [comment]
Thank you
