### ISSUE TITLE
Mailchimp V3

### ISSUE THREAD

**Issue by gregory-claeyssens** [skovmand/mailchimp-laravel#7]
Version 3.0 of the mailchimp API is available.
Time to upgrade?

**Comment by nacr** [comment]
Hello,

is this a problem?

**Comment by gregory-claeyssens** [comment]
Wel MailChimp states:

MailChimp API v3.0 is now live!
Prior versions have been deprecated, so all API users should begin transitioning to v3.0.

**Comment by skovmand** [comment]
Hi. Thanks for your suggestions and for your patience. I've been busy.

Looked at it tonight, and correct me if I'm wrong. It seems the [mailchimp/mailchimp](https://packagist.org/packages/mailchimp/mailchimp) php package maintained by Mandrill has not yet been updated to support v3. Until that I can't upgrade this package to v3 either.

**Comment by gregory-claeyssens** [comment]
Oh right, my bad.
