### ISSUE TITLE
associative array issue

### ISSUE THREAD

**Issue by rajankarthiks** [skovmand/mailchimp-laravel#8]
Hi,

I am facing the email error while i am sending a request to subscribe function (Validation error: {"email":"Please enter a struct\/associative array"})
Is the issue fixed?

Awaiting for your response at the earliest.

Thank you

**Comment by skovmand** [comment]
I have no problems at my end. Can you tell me how to reproduce it?

**Comment by rajankarthiks** [comment]
I am passing the variables to mailchimp subscribe function something like this:

$merge_vars = array(
                    'MERGE1'=>guestName,
                    'MERGE10'=>date('m/d/Y'),
                    'MERGE27'=>date("m/d/Y",strtotime(reservationDate))
                );
                $this->mailchimp->lists->subscribe($this->listId,$_POST['email'],$merge_vars,"html",false,true );

This was working fine some days back, but now recently it is started giving me the error. I am also tried something like below but that also does not seems to be working:

$this->mailchimp->lists->subscribe($this->listId, ['email' => $_POST['email']],$merge_vars,"html",false,true );

**Comment by rajankarthiks** [comment]
Awaiting for your reply.

**Comment by skovmand** [comment]
Hi again.

The problem must be in the mailchimp/mailchimp package which is a dependency for this package.

This package is not dealing with the api calls, but only instantiates an instance of the mailchimp class.

**Comment by rajankarthiks** [comment]
Great thanks!!

**Comment by imjaysoninfante** [comment]
Hi Sir Skovmand, I use your skovmand/mailchimp on my laravel 5 it was a great stuff, however I got a error from this code block
catch(\Mailchimp_Error $e){
            // do something
            return 'Mailchimp error occur';
   }

what does it mean?

Thanks
