### ISSUE TITLE
Email not added to newsletter list id.

### ISSUE THREAD

**Issue by sameernyaupane** [skovmand/mailchimp-laravel#9]
Hi there, thanks  for the work you've done on this.

The email subscription goes though without any exception, but the email doesn't appear in the mailchimp dasbhoard on the respective newsletter list id.

Is there some issue with the code or did the API parameters change?

Here's my code just in case I did something wrong, that could be pointed out:

`$mailchimp = new MailchimpService;
 $mailchimp->addEmailToList($command->email);`

Thanks a lot again!

**Comment by skovmand** [comment]
Hi!

Everythings is working fine at my end. I'm not sure what the problem is. 
Are you still having the problem?

Remember, my service is really only pulling the service out of the IOC-container with your key. Maybe the issue is with the mailchimp/mailchimp package?

Regards, Niels.

**Comment by sameernyaupane** [comment]
yea seems like so the mailchimp package has an issue then. I have set the key on config/mailchimp.php . Is there anything else missing from my side? Thanks

**Comment by sameernyaupane** [comment]
Sorry, I got this sorted. I had to actually click on the subscribe button sent on the email by Mailchimp to be added to dashboard. I assumed it was automatically added to the dashboard, but its not so. 
Sorry for the hassle. Let me close this, since its not an issue.
